### ISSUE TITLE
App referencing out-of-date data layer

### ISSUE THREAD

**Issue by pribbens** [matia-gov/LicensedContractorFinder#8]
Based on lines 181-183 of App.vue it looks like the app is referencing the old, out-of-date version of the Trade Licenses data layer on DataBridge: "li_trade_licenses". It should be referencing the new version: "trade_licenses". @m-atia is this something you could fix easily?

**Comment by m-atia** [comment]
I can update this easily.

**Comment by m-atia** [comment]
This has been updated!

**Comment by pribbens** [comment]
Awesome, thanks, Moh! It looks like it's working, although only after I cleared my cache did I see the updated data. For people who don't know to clear their cache will it automatically show the updated data no matter what at some point?
